server:
  port: 9000
  
spring:
  rabbitmq:
    host: 192.168.179.6
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
#    host:
#        connect-timeout-millis: 10000
#        socket-timeout-millis: 60000
    routes:
      product-service: /gateway/product/**
      order-service: /gateway/order/**
    sensitive-headers:
#    ignored-services: order-service, product-service #/*-service/**

#hystrix:
#    command:
#        default:
#            execution:
#                isolation:
#                    thread:
#                        timeoutInMilliseconds: 60000
