server:
  port: 8781

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  redis:
    database: 0
    host: 192.168.179.6
    port: 6379
    timeout: 2000
  rabbitmq:
    host: 192.168.179.6
    port: 5672
    username: guest
    password: guest

product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  client:
    config:
      default:
        connectTimeout: 7000
        readTimeout: 7000
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
#        timeout:
#          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 6000

management:
  endpoints:
    web:
      exposure:
        include: "*"
